name       : bullet3
version    : '3.08'
release    : 13
source     :
    - https://github.com/bulletphysics/bullet3/archive/3.08.tar.gz : 05826c104b842bcdd1339b86894cb44c84ac2525ac296689d34b38a14bbba0dd
license    :
    - BSD-3-Clause
    - Zlib
component  : programming.library
summary    : 3D Collision and Dynamics library
description: |
    A 3D Collision Detection and Rigid Body Dynamics Library for games and animation.
libsplit   : no
builddeps  :
    - pkgconfig(python3)
setup      : |
    %cmake_ninja \
        -DBUILD_SHARED_LIBS=ON \
        -DCLSOCKET_SHARED=ON \
        -DINSTALL_EXTRA_LIBS=ON \
        -DINSTALL_LIBS=ON \
        -DLIB_SUFFIX=64
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
