name       : bullet3
version    : '2.89'
release    : 12
source     :
    - https://github.com/bulletphysics/bullet3/archive/2.89.tar.gz : 621b36e91c0371933f3c2156db22c083383164881d2a6b84636759dc4cbb0bb8
license    :
    - BSD-3-Clause
    - Zlib
component  : programming.library
summary    : 3D Collision and Dynamics library
description: |
    A 3D Collision Detection and Rigid Body Dynamics Library for games and animation
libsplit   : no
builddeps  :
    - pkgconfig(python3)
setup      : |
    mkdir build && cd build
    %cmake -DBUILD_SHARED_LIBS=ON \
           -DCLSOCKET_SHARED=ON \
           -DINSTALL_EXTRA_LIBS=ON \
           -DLIB_SUFFIX=64 \
           -DBUILD_OPENGL3_DEMOS=ON \
           -DBUILD_UNIT_TESTS=ON \
           ..
build      : |
    %make -C build
install    : |
    %make_install -C build
check      : |
    %make test -C build
