name       : bullet3
version    : '3.17'
release    : 14
source     :
    - https://github.com/bulletphysics/bullet3/archive/refs/tags/3.17.tar.gz : baa642c906576d4d98d041d0acb80d85dd6eff6e3c16a009b1abf1ccd2bc0a61
license    :
    - BSD-3-Clause
    - Zlib
component  : programming.library
summary    : 3D Collision and Dynamics library
description: |
    A 3D Collision Detection and Rigid Body Dynamics Library for games and animation.
libsplit   : no
builddeps  :
    - pkgconfig(python3)
setup      : |
    %cmake_ninja \
        -DBUILD_SHARED_LIBS=ON \
        -DCLSOCKET_SHARED=ON \
        -DINSTALL_EXTRA_LIBS=ON \
        -DINSTALL_LIBS=ON \
        -DLIB_SUFFIX=64
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
