name       : bullet3
version    : 2.86.1
release    : 6
source     :
    - https://github.com/bulletphysics/bullet3/archive/2.86.1.tar.gz : c058b2e4321ba6adaa656976c1a138c07b18fc03b29f5b82880d5d8228fbf059
license    :
    - BSD-3-Clause
    - zlib
component  : programming.library
summary    : 3D Collision and Dynamics library
description: |
    A 3D Collision Detection and Rigid Body Dynamics Library for games and animation
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(lua-5.1)
setup      : |
    mkdir build
    cd build
    %cmake -DCMAKE_BUILD_TYPE=Release \
           -DBUILD_SHARED_LIBS=ON \
           -DBUILD_OPENGL3_DEMOS=ON \
           -DINSTALL_EXTRA_LIBS=ON \
           -DLIB_SUFFIX=64 \
           ..
build      : |
    cd build
    %make
install    : |
    cd build
    %make_install
