name       : bullet3
version    : 2.83.7
release    : 2
source     :
    - https://github.com/bulletphysics/bullet3/archive/2.83.7.tar.gz : 00d1d8f206ee85ffd171643ac8e72f9f4e0bf6dbf3d4ac55f4495cb168b51243
license    :
    - BSD-3-Clause
    - zlib
component  : programming.library
summary    : 3D Collision and Dynamics library
description: |
    A 3D Collision Detection and Rigid Body Dynamics Library for games and animation
setup      : |
    mkdir -p build
    cd build
    %cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON -DLIB_SUFFIX=64 ..
build      : |
    cd build
    %make
install    : |
    cd build
    %make_install
