name       : bullet3
version    : '3.24'
release    : 18
source     :
    - https://github.com/bulletphysics/bullet3/archive/refs/tags/3.24.tar.gz : 6b1e987d6f8156fa8a6468652f4eaad17b3e11252c9870359e5bca693e35780b
license    :
    - BSD-3-Clause
    - Zlib
component  : programming.library
summary    : 3D Collision and Dynamics library
description: |
    A 3D Collision Detection and Rigid Body Dynamics Library for games and animation.
libsplit   : no
builddeps  :
    - pkgconfig(python3)
setup      : |
    %cmake_ninja \
        -DBUILD_SHARED_LIBS=ON \
        -DCLSOCKET_SHARED=ON \
        -DINSTALL_EXTRA_LIBS=ON \
        -DINSTALL_LIBS=ON \
        -DLIB_SUFFIX=64 \
        -DUSE_DOUBLE_PRECISION=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
