name       : bullet3
version    : 2.87
release    : 8
source     :
    - https://github.com/bulletphysics/bullet3/archive/2.87.tar.gz : 438c151c48840fe3f902ec260d9496f8beb26dba4b17769a4a53212903935f95
license    :
    - BSD-3-Clause
    - Zlib
component  : programming.library
summary    : 3D Collision and Dynamics library
description: |
    A 3D Collision Detection and Rigid Body Dynamics Library for games and animation
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(python3)
setup      : |
    mkdir build && cd build
    %cmake -DBUILD_SHARED_LIBS=ON \
           -DCLSOCKET_SHARED=ON \
           -DINSTALL_EXTRA_LIBS=ON \
           -DLIB_SUFFIX=64 \
           -DBUILD_OPENGL3_DEMOS=ON \
           -DBUILD_UNIT_TESTS=ON \
           ..
build      : |
    cd build
    %make
install    : |
    cd build
    %make_install
check      : |
    cd build
    %make test
